#! /bin/sh
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI1 -d 9 10

bspc config border_width         0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config initial_polarity second_child

bspc rule -a Firefox desktop='1'
bspc rule -a Atom desktop='2'
bspc rule -a TeamSpeak 3 desktop='2'
bspc rule -a keepassxc desktop='4'
bspc rule -a Thunderbird desktop='5'
bspc rule -a "Mullvad VPN" desktop='6'

sh /home/tobias/.screenlayout/checkscreens.sh 1 &
dunst &
setxkbmap de
xsetroot -cursor_name left_ptr
xrdb merge ~/.Xresources &
xbacklight -set 30
pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo 50%
pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo 1
# compton --config ~/.config/compton/compton.conf &


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
