#! /bin/sh
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       false
bspc config initial_polarity second_child
bspc config automatic_scheme longest_side

bspc rule -a Firefox desktop='1'
bspc rule -a Thunderbird desktop='9'
bspc rule -a keepassxc desktop='10'
bspc rule -a KeeWeb desktop='10'

~/.config/scripts/physlock.sh &
wmname LG3D
sxhkd &
dunst &
setxkbmap de
xsetroot -cursor_name left_ptr
xrdb merge ~/.Xresources &
wal -i ~/.config/background
~/.config/polybar/launch.sh &
compton --config ~/.config/compton/compton.conf &
sleep 3
keepassxc &
thunderbird &
firefox &

xset s 300
xss-lock -- ~/.config/scripts/physlock.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
